import { randomUUID } from "node:crypto";
import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import { SESSION_COOKIE_NAME, verifySessionToken } from "@/lib/session";
import { ensureDatabaseSchema, turso } from "@/lib/turso";

type GenerateRacesBody = {
  divisionId?: string;
  raceType?: "heat" | "tournament";
  phaseName?: string;
  laneCount?: number;
};

type CarRow = {
  id: string;
};

export async function POST(request: Request) {
  const cookieStore = await cookies();
  const token = cookieStore.get(SESSION_COOKIE_NAME)?.value;
  const session = token ? await verifySessionToken(token) : null;

  if (!session) {
    return NextResponse.json({ error: "Unauthorized." }, { status: 401 });
  }

  const body = (await request.json()) as GenerateRacesBody;
  const divisionId = body.divisionId?.trim();
  const raceType = body.raceType === "tournament" ? "tournament" : "heat";
  const phaseName = (body.phaseName ?? "").trim() || (raceType === "tournament" ? "Tournament" : "Qualifying");
  const laneCount = Number.isInteger(body.laneCount) ? Number(body.laneCount) : 4;

  if (!divisionId) {
    return NextResponse.json({ error: "divisionId is required." }, { status: 400 });
  }

  if (laneCount < 1 || laneCount > 8) {
    return NextResponse.json({ error: "Lane count must be between 1 and 8." }, { status: 400 });
  }

  await ensureDatabaseSchema();

  const divisionLookup = await turso.execute({
    sql: "SELECT id, event_id, name FROM divisions WHERE id = ? LIMIT 1",
    args: [divisionId],
  });

  if (divisionLookup.rows.length === 0) {
    return NextResponse.json({ error: "Division not found." }, { status: 404 });
  }

  const divisionRow = divisionLookup.rows[0];
  const eventId = String(divisionRow.event_id ?? "");
  const divisionName = String(divisionRow.name ?? "Division");

  const carsResult = await turso.execute({
    sql: `SELECT id
          FROM cars
          WHERE division_id = ?
            AND registration_status IN ('registered', 'checked_in', 'approved')
          ORDER BY car_number ASC`,
    args: [divisionId],
  });

  const cars = carsResult.rows as unknown as CarRow[];

  if (cars.length === 0) {
    return NextResponse.json(
      {
        error:
          "No eligible cars found in this division. Register/assign cars first, then generate races.",
      },
      { status: 409 }
    );
  }

  const phaseId = randomUUID();
  const phaseType = raceType === "tournament" ? "tournament" : "qualifying";
  const tournamentFormat = raceType === "tournament" ? "single_elimination" : null;
  const seedingMethod = raceType === "heat" ? "best_time" : null;
  const racesNeeded = Math.ceil(cars.length / laneCount);
  const createdRaceIds: string[] = [];

  try {
    await turso.execute({
      sql: `INSERT INTO phases (
              id,
              event_id,
              division_id,
              phase_type,
              name,
              status,
              tournament_format,
              seeding_method,
              sort_order
            ) VALUES (?, ?, ?, ?, ?, 'pending', ?, ?, 0)`,
      args: [phaseId, eventId, divisionId, phaseType, phaseName, tournamentFormat, seedingMethod],
    });

    let carIndex = 0;
    for (let raceNumber = 1; raceNumber <= racesNeeded; raceNumber += 1) {
      const raceId = randomUUID();
      createdRaceIds.push(raceId);

      await turso.execute({
        sql: "INSERT INTO races (id, phase_id, race_number, race_status, notes) VALUES (?, ?, ?, 'pending', ?)",
        args: [raceId, phaseId, raceNumber, `Generated by ${session.email}`],
      });

      for (let laneNumber = 1; laneNumber <= laneCount; laneNumber += 1) {
        const carId = carIndex < cars.length ? String(cars[carIndex].id) : null;
        if (carId) {
          carIndex += 1;
        }

        await turso.execute({
          sql: "INSERT INTO race_lanes (id, race_id, lane_number, car_id) VALUES (?, ?, ?, ?)",
          args: [randomUUID(), raceId, laneNumber, carId],
        });
      }
    }

    return NextResponse.json({
      message: `Generated ${createdRaceIds.length} ${raceType} races for ${divisionName}.`,
      phaseId,
      raceIds: createdRaceIds,
      racesCreated: createdRaceIds.length,
      carsIncluded: cars.length,
      laneCount,
      divisionId,
    });
  } catch (error) {
    const details = String(error);
    return NextResponse.json({ error: `Failed to generate races: ${details}` }, { status: 500 });
  }
}
